# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'отметки в отделениях',
                'verbose_name': 'Отметка в одтелении',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.ManyToManyField(blank=True, null=True, to='logistapp.Elevation')),
            ],
            options={
                'verbose_name_plural': 'Объекты доставки',
                'verbose_name': 'Объект доставки',
            },
        ),
        migrations.CreateModel(
            name='PostOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Почтовые офисы',
                'verbose_name': 'Почтовый офис',
            },
        ),
        migrations.AddField(
            model_name='elevation',
            name='post_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistapp.PostOffice'),
        ),
    ]
