# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='path',
            field=models.ManyToManyField(to='logistapp.Elevation'),
        ),
    ]
