# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistapp', '0002_auto_20171029_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('letter', 'Letter'), ('parcel_post', 'Parcel post'), ('small_package', 'Small package'), ('package', 'Package')], default='package', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('adopted', 'Adopted at'), ('treatment', 'Treatment'), ('route', 'En route'), ('awaits', 'Awaits delivery'), ('delivered', 'Delivered')], default='route', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=100, max_digits=10),
            preserve_default=False,
        ),
    ]
