# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistapp', '0004_auto_20171030_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='recipient',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='sender',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
