# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistapp', '0005_auto_20171030_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='path',
            field=models.ManyToManyField(blank=True, null=True, to='logistapp.Elevation'),
        ),
    ]
