# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('logistapp', '0006_auto_20171030_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='postoffice',
            name='index',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
