# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistapp', '0007_postoffice_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevation',
            name='type',
            field=models.CharField(choices=[('in', 'In'), ('out', 'Out')], default='in', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postoffice',
            name='index',
            field=models.CharField(default=796246, max_length=255),
        ),
    ]
