# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistapp', '0008_auto_20171030_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elevation',
            options={'ordering': ['datetime'], 'verbose_name': 'Отметка в одтелении', 'verbose_name_plural': 'отметки в отделениях'},
        ),
        migrations.AlterField(
            model_name='postoffice',
            name='index',
            field=models.CharField(default=246130, max_length=255),
        ),
    ]
